"""empty message

Revision ID: 28cca5e08257
Revises: 77315111fa29
Create Date: 2026-08-11 11:41:01.579143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28cca5e08257'
down_revision = '77315111fa29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_user_name'))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index(batch_op.f('ix_users_user_name'), ['user_name'], unique=True)
        batch_op.drop_column('username')

    # ### end Alembic commands ###
