"""empty message

Revision ID: 77315111fa29
Revises: 89f2225765be
Create Date: 2026-08-11 09:33:33.183237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77315111fa29'
down_revision = '89f2225765be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=127), nullable=False),
    sa.Column('category_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_category_name'), ['category_name'], unique=True)

    op.create_table('interventiontypes',
    sa.Column('interventiontype_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interventiontype_name', sa.String(length=127), nullable=False),
    sa.Column('interventiontype_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('interventiontype_id'),
    sa.UniqueConstraint('interventiontype_name')
    )
    op.create_table('priorities',
    sa.Column('priority_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('priority_name', sa.String(length=31), nullable=False),
    sa.Column('priority_level', sa.Integer(), nullable=False),
    sa.Column('priority_delay_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('priority_id')
    )
    with op.batch_alter_table('priorities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_priorities_priority_name'), ['priority_name'], unique=True)

    op.create_table('sites',
    sa.Column('site_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_name', sa.String(length=127), nullable=False),
    sa.Column('site_address', sa.String(length=255), nullable=True),
    sa.Column('site_city', sa.String(length=63), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('site_id')
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sites_site_name'), ['site_name'], unique=True)

    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_name', sa.String(length=63), nullable=False),
    sa.Column('tag_color', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('tag_id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_tag_name'), ['tag_name'], unique=True)

    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_name', sa.String(length=127), nullable=False),
    sa.Column('team_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('team_id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_team_name'), ['team_name'], unique=True)

    op.create_table('equipments',
    sa.Column('equipment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_name', sa.String(length=255), nullable=True),
    sa.Column('equipment_type', sa.String(length=127), nullable=True),
    sa.Column('equipment_serial', sa.String(length=127), nullable=False),
    sa.Column('equipment_purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('equipment_id')
    )
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipments_equipment_serial'), ['equipment_serial'], unique=True)

    op.create_table('knowledgesarticles',
    sa.Column('article_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_title', sa.String(length=255), nullable=False),
    sa.Column('article_content', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_table('tickets',
    sa.Column('ticket_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_title', sa.String(length=63), nullable=False),
    sa.Column('ticket_description', sa.Text(), nullable=True),
    sa.Column('ticket_status', sa.Enum('NEW', 'PENDING', 'SOLVED', 'CLOSED', name='ticketstatus'), nullable=False),
    sa.Column('ticket_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('priority_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.equipment_id'], ),
    sa.ForeignKeyConstraint(['priority_id'], ['priorities.priority_id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_table('attachments',
    sa.Column('attachment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attachment_filename', sa.String(length=255), nullable=False),
    sa.Column('attachment_path', sa.Text(), nullable=True),
    sa.Column('attachment_size', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment_content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('interventions',
    sa.Column('intervention_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intervention_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('intervention_duration', sa.Integer(), nullable=True),
    sa.Column('intervention_report', sa.Text(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('interventiontype_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['interventiontype_id'], ['interventiontypes.interventiontype_id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ),
    sa.PrimaryKeyConstraint('intervention_id')
    )
    op.create_table('satisfactionsurveys',
    sa.Column('survey_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('survey_rating', sa.Integer(), nullable=False),
    sa.Column('survey_comment', sa.Text(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ),
    sa.PrimaryKeyConstraint('survey_id'),
    sa.UniqueConstraint('ticket_id')
    )
    op.create_table('ticket_tags',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ),
    sa.PrimaryKeyConstraint('ticket_id', 'tag_id')
    )
    op.create_table('ticketstatushistories',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.Enum('NEW', 'PENDING', 'SOLVED', 'CLOSED', name='ticketstatus'), nullable=True),
    sa.Column('new_status', sa.Enum('NEW', 'PENDING', 'SOLVED', 'CLOSED', name='ticketstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.drop_table('basket_items')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_name'))

    op.drop_table('items')
    op.drop_table('baskets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('user_email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('user_password', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('user_firstname', sa.String(length=127), nullable=False))
        batch_op.add_column(sa.Column('user_lastname', sa.String(length=127), nullable=False))
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index(batch_op.f('ix_users_user_email'), ['user_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_user_name'), ['user_name'], unique=True)
        batch_op.create_foreign_key(None, 'teams', ['team_id'], ['team_id'])
        batch_op.create_foreign_key(None, 'sites', ['site_id'], ['site_id'])
        batch_op.drop_column('description')
        batch_op.drop_column('email')
        batch_op.drop_column('username')
        batch_op.drop_column('password')
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_user_name'))
        batch_op.drop_index(batch_op.f('ix_users_user_email'))
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.drop_column('site_id')
        batch_op.drop_column('team_id')
        batch_op.drop_column('user_lastname')
        batch_op.drop_column('user_firstname')
        batch_op.drop_column('user_password')
        batch_op.drop_column('user_email')
        batch_op.drop_column('user_name')

    op.create_table('baskets',
    sa.Column('basket_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('closed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('baskets_user_id_fkey')),
    sa.PrimaryKeyConstraint('basket_id', name=op.f('baskets_pkey'))
    )
    op.create_table('items',
    sa.Column('item_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('item_id', name=op.f('items_pkey'))
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_name'), ['name'], unique=True)

    op.create_table('basket_items',
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('basket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.basket_id'], name=op.f('basket_items_basket_id_fkey')),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], name=op.f('basket_items_item_id_fkey')),
    sa.PrimaryKeyConstraint('item_id', 'basket_id', name=op.f('basket_items_pkey'))
    )
    op.drop_table('ticketstatushistories')
    op.drop_table('ticket_tags')
    op.drop_table('satisfactionsurveys')
    op.drop_table('interventions')
    op.drop_table('comments')
    op.drop_table('attachments')
    op.drop_table('tickets')
    op.drop_table('knowledgesarticles')
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipments_equipment_serial'))

    op.drop_table('equipments')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_team_name'))

    op.drop_table('teams')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_tag_name'))

    op.drop_table('tags')
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sites_site_name'))

    op.drop_table('sites')
    with op.batch_alter_table('priorities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_priorities_priority_name'))

    op.drop_table('priorities')
    op.drop_table('interventiontypes')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_category_name'))

    op.drop_table('categories')
    # ### end Alembic commands ###
