"""empty message

Revision ID: eef82aa03c51
Revises: 28cca5e08257
Create Date: 2026-08-13 06:28:30.728278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef82aa03c51'
down_revision = '28cca5e08257'
branch_labels = None
depends_on = None


def upgrade():
    role_status_enum = sa.Enum('CLIENT', 'TECHNICIEN', 'ADMIN', name='rolestatus')
    role_status_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('role_name',
            existing_type=sa.VARCHAR(length=50),
            type_=role_status_enum,
            existing_nullable=False,
            postgresql_using='role_name::rolestatus'
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('role_name',
            existing_type=sa.Enum('CLIENT', 'TECHNICIEN', 'ADMIN', name='rolestatus'),
            type_=sa.VARCHAR(length=50),
            existing_nullable=False
        )
    sa.Enum(name='rolestatus').drop(op.get_bind())        
    # ### end Alembic commands ###
